site_name: tanu
site_description: High-performance, async-friendly WebAPI testing framework for Rust
site_url: https://tanu-rs.github.io/tanu/
repo_name: tanu-rs/tanu
repo_url: https://github.com/tanu-rs/tanu
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025&ndash;2026 Yukinari Tani

theme:
  name: material
  favicon: assets/tanu.png
  logo: assets/tanu.png
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Follow the operating system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Guide:
      - Getting Started: getting-started.md
      - Writing Tests:
          - Test Attributes: attribute.md
          - Assertions: assertion.md
          - Ordered Execution: ordered-execution.md
      - Protocols:
          - gRPC: grpc.md
          - GraphQL: graphql.md
      - Running Tests:
          - Configuration: configuration.md
          - Command Line Options: command-line-option.md
          - TUI: tui.md
          - Reporters: report.md
  - Best Practices: best-practices.md
  - FAQ: faq.md
  - API Reference: https://docs.rs/tanu
validation:
  omitted_files: info
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
not_in_nav: |
  /tags.md
  /includes/
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mike

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tanu-rs/tanu
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/tanu
  tags:
    HTTP: http
    gRPC: grpc
    Testing: testing
    Configuration: config
    API: api
    Rust: rust
