[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tanu = { path = "../../tanu" }
tokio = { workspace = true }
url = { version = "2", features = ["serde"] }
