name: publish-docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Configure git author
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.11"
    - name: Sync dependencies
      run: uv sync --frozen
    - name: Build and deploy documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run mkdocs gh-deploy --force --clean
