name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
          --default-toolchain stable \
          --profile minimal \
          --component rustfmt clippy \
          -y
    - name: build crates and examples
      run: |
        cargo build --workspace --all-targets --all-features
    - name: run clippy
      run: |
        cargo clippy --workspace --all-targets --all-features -- --deny clippy::all
    - name: install nextest
      uses: taiki-e/install-action@nextest
    - name: run unit tests
      run: cargo nextest run --retries 3
